/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.avrsandbox.snaploader;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class LibraryTest {
    
    @Test 
    void someLibraryMethodReturnsTrue() {
    }
}
